### ISSUE TITLE
React engine generates checksum warning when directly launch the server page "http://localhost:8000/trends"

### ISSUE THREAD

**Issue by williamku** [ufocoder/redux-universal-boilerplate#4] opened 2016-08-14 21:59 UTC
ufocoder, 

First of all, deeply appreciate this boilerplace.   Very nicely done!  

But I am seeing a following warning when launching a page (http://localhost:8000/trends) that requires async data fetching on the server side:  

client.js:9281 Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) <!-- react-empty: 1 -
 (server) <div data-reactroot="

I also observed that the rendering actually is done 2 times:  one is the direct server HTML output being rendered.  Then the React engine will render it again because the "checksum" mismatch.  Then the React engine also thrown the above warning to the console.  The view actually flickers upon the 2nd rendering.    

One of the major benefit for the "universal/isomorphic" rendering is efficiency - to allow user see the page quicker.   With this 2-time rendering, this advantage is lost.   Any chance you could find a solution for it?   

Thanks again!
William

**Comment by ufocoder** [comment] 2016-08-15 04:09
@williamku Thank you for feedback, I have a solution, I try to fix this issue on this week.

**Comment by ufocoder** [comment] 2016-08-15 06:50
@williamku It was fixed by https://github.com/ufocoder/redux-universal-boilerplate/commit/73ff62100b05822bc45e3776e66c7b8689cfa3af, but It's not a pretty good solution.

I believe my question will answered there https://github.com/makeomatic/redux-connect/issues/62 and I will improve boilerplate

**Closed as completed by ufocoder** 2016-08-15 06:50 UTC
Labels: bug

**Comment by williamku** [comment] 2016-08-15 13:19
ufocoder,

not sure if you are able to receive my this reply since the mail was
originated from github.

First of all, Thanks for the quick turn-around!

I got your latest fix and it worked to certain extent - at least the React
warning is no longer present.   But the server side generated HTML content
seems there is a flickering problem.   To find out why, I turned off the
javscript on Chrome and I got the server side HTML which look like this:

[image: Inline image 1]

Clearly, it looked much different from the final result.    Then, after
this initial rendering, somehow, the client side style has to be applied
--- i think this is the reason for flickering.   I would ideal that this
flickering can be resolved...

But regardless, I want to thank you very much for the quick turn-around.

You have a great day!

William

**Comment by ufocoder** [comment] 2016-08-15 13:51
@williamku I can't view your attached image, please check it.

Boilerplate can works in two ways:
1) build bundlers and run server - use this way for deployment
2) watch mode - use this way for development

In `watch mode` all modules load one by one as well as style modules that why You see html layout and flickering is appear but then this layout will be stylized in moment. There's behavior caused by webpack configuration for `watch` mode.

But if you run `build`  command and then run server You will get proper way of work for styles.

Check [README.md](https://github.com/ufocoder/redux-universal-boilerplate/blob/master/README.md) also, please.

**Comment by williamku** [comment] 2016-08-15 15:19
ufocoder,

Sorry about the missing image --- i copy-and-pasted in inline - that may be
the reason that it was missing...

Let me include that image here as attachment.   Hope it will be picked up
on your side...

I don't think this leftover issue is a big deal.  So please resolve it only
if it is convenient for you to do so...

Thanks again...

William

**Comment by ufocoder** [comment] 2016-08-15 15:31
@williamku To attach image write a URL to image, then [open this thread directly](https://github.com/ufocoder/redux-universal-boilerplate/issues/4) at github.com to check the result. Don't use your mail agent because it doesn't attach image properly.
